name: Metrics
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: assets
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: github-snake.svg?palette=github-dark
          committer_branch: assets
#       - name: Deploy
#         uses: exuanbo/actions-deploy-gist@v1
#         with:
#           token: ${{ secrets.METRICS_TOKEN }}
#           file_path: github-snake.svg
#           file_type: binary
#           committer_branch: assets
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.skyline.city.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          committer_branch: assets
          plugin_skyline: yes
          plugin_skyline_year: 2023
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          plugin_skyline_settings: |
            {
              "url": "https://honzaap.github.io/GithubCity?name=${login}&year=${year}",
              "ready": "[...document.querySelectorAll('.display-info span')].map(span => span.innerText).includes('${login}')",
              "wait": 4,
              "hide": ".github-corner, .footer-link, .buttons-options, .mobile-rotate, .display-info span:first-child"
            }
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          committer_branch: assets
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.people.followers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          committer_branch: assets
          plugin_people: yes
          plugin_people_types: followers
      - name: Squash and Commit
        run: |
          git add .
          git reset --soft HEAD~
          git commit -m "chore: update assets [skip ci]"
          git push -f
